name: task_for_uicgroup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.9
  dio: ^5.8.0+1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.2.3
  google_maps_flutter: ^2.12.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  logger: ^2.6.0
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  freezed: ^3.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen/Sen-VariableFont_wght.ttf