name: task_for_uicgroup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  go_router: ^15.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen/Sen-VariableFont_wght.ttf